In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/product_catalog_with_descriptions.csv.csv')

In [3]:
df

,Assessment Name,URL,Remote Support,Adaptive Support,Types,Description,Job Levels,Languages,Assessment Length
0,Account Manager Solution,https://www.shl.com/solutions/products/product...,Yes,Yes,"C, P, A, B",The Account Manager solution is an assessment ...,"Mid-Professional,","English (USA),",Approximate Completion Time in minutes = 49
1,Administrative Professional - Short Form,https://www.shl.com/solutions/products/product...,Yes,Yes,"A, K, P",The Administrative Professional solution is fo...,"Entry-Level,","English (USA),",Approximate Completion Time in minutes = 36
2,Agency Manager Solution,https://www.shl.com/solutions/products/product...,Yes,Yes,"A, B, P, S",The Agency Manager solution is for mid-level s...,"Front Line Manager, Manager, Supervisor,","English (USA),",Approximate Completion Time in minutes = 51
3,Apprentice + 8.0 Job Focused Assessment,https://www.shl.com/solutions/products/product...,Yes,No,"B, P",The Apprentice + 8.0 Job-Focused Assessment is...,"General Population, Graduate, Entry-Level,","English International, German,",Approximate Completion Time in minutes = 30
4,Apprentice 8.0 Job Focused Assessment,https://www.shl.com/solutions/products/product...,Yes,No,"B, P",The Apprentice 8.0 Job-Focused Assessment is a...,"Entry-Level, General Population, Graduate,","English International, German, French,",Approximate Completion Time in minutes = 20
...,...,...,...,...,...,...,...,...,...
479,Written English v1,https://www.shl.com/solutions/products/product...,Yes,Yes,K,The Written English test measures knowledge of...,"Entry-Level, Front Line Manager, Mid-Professio...","English (USA), English International,",Approximate Completion Time in minutes = 30
480,Written Spanish,https://www.shl.com/solutions/products/product...,Yes,Yes,K,This test measures knowledge of Spanish gramma...,"Entry-Level, Front Line Manager, Mid-Professio...","Latin American Spanish,",Approximate Completion Time in minutes = 22
481,Zabbix (New),https://www.shl.com/solutions/products/product...,Yes,No,K,Multi-choice test that measures the knowledge ...,"Mid-Professional, Professional Individual Cont...","English (USA),",Approximate Completion Time in minutes = 9
482,360 Digital Report,https://www.shl.com/solutions/products/product...,Yes,No,D,Introducing the new 360 Digital Report from SH...,"Director, Manager, Entry-Level, Executive, Fro...",Not Found,Not Found
483,360° Multi-Rater Feedback System (MFS),https://www.shl.com/solutions/products/product...,Yes,No,D\nP,"SHL 360, or the Multi-Rater Feedback System (‘...","Director, Executive, Front Line Manager, Manag...","Latin American Spanish, Romanian, French (Cana...",Approximate Completion Time in minutes = Untimed

In [8]:
df["Assessment Length (minutes)"] = df["Assessment Length"].apply(parse_time)

In [9]:
df.head()

,Assessment Name,URL,Remote Support,Adaptive Support,Types,Description,Job Levels,Languages,Assessment Length,Duration (Minutes),Assessment Length (minutes)
0,Account Manager Solution,https://www.shl.com/solutions/products/product...,Yes,Yes,"C, P, A, B",The Account Manager solution is an assessment ...,"Mid-Professional,","English (USA),",Approximate Completion Time in minutes = 49,NaN,49
1,Administrative Professional - Short Form,https://www.shl.com/solutions/products/product...,Yes,Yes,"A, K, P",The Administrative Professional solution is fo...,"Entry-Level,","English (USA),",Approximate Completion Time in minutes = 36,NaN,36
2,Agency Manager Solution,https://www.shl.com/solutions/products/product...,Yes,Yes,"A, B, P, S",The Agency Manager solution is for mid-level s...,"Front Line Manager, Manager, Supervisor,","English (USA),",Approximate Completion Time in minutes = 51,NaN,51
3,Apprentice + 8.0 Job Focused Assessment,https://www.shl.com/solutions/products/product...,Yes,No,"B, P",The Apprentice + 8.0 Job-Focused Assessment is...,"General Population, Graduate, Entry-Level,","English International, German,",Approximate Completion Time in minutes = 30,NaN,30
4,Apprentice 8.0 Job Focused Assessment,https://www.shl.com/solutions/products/product...,Yes,No,"B, P",The Apprentice 8.0 Job-Focused Assessment is a...,"Entry-Level, General Population, Graduate,","English International, German, French,",Approximate Completion Time in minutes = 20,NaN,20

In [35]:
df['Assessment Length'].isnull().value_counts()

Assessment Length
False    484
Name: count, dtype: int64

In [ ]:
import pandas as pd
import re

# Load your cleaned CSV


# Function to convert time strings to minutes
def convert_time_to_minutes(time_str):
    if pd.isnull(time_str):
        return None
    time_str = str(time_str).lower()

    if "Untimed" in time_str:
        return 9999  # Represents untimed assessments

    if "not found" in time_str:
        return None  # Missing data to be handled separately

    match = re.search(r"(\d+)\s*(minute|min)", time_str)
    if match:
        return int(match.group(1))

    match = re.search(r"(\d+)\s*hour", time_str)
    if match:
        return int(match.group(1)) * 60

    return None  # fallback

# Apply the function
df["Duration (Minutes)"] = df["Assessment Length"].apply(convert_time_to_minutes)

# Optional: Fill missing durations ("not found") using average per Type or just global average


# Save cleaned version
df.to_csv("shl_product_catalog_final.csv", index=False)
print("✅ Cleaned data saved to 'shl_product_catalog_final.csv'")

✅ Cleaned data saved to 'shl_product_catalog_final.csv'

In [27]:
final_df = pd.read_csv('./shl_product_catalog_final.csv')

In [10]:
df['Assessment Length (minutes)'].value_counts()

Assessment Length (minutes)
-1     65
 10    31
 9     27
 20    24
 8     22
       ..
 68     1
 66     1
 61     1
 52     1
 2      1
Name: count, Length: 62, dtype: int64

In [11]:
import pandas as pd

# Load the cleaned spreadsheet


# Normalize the 'Assessment Length' column
assessment_lengths = df["Assessment Length"].astype(str).str.lower().str.strip()

# Count values that indicate unknown or not provided time
unknown_keywords = ["not found", "tbc", "n/a", "-", "variable"]
counts = {kw: assessment_lengths.str.contains(kw).sum() for kw in unknown_keywords}
total_unknown = sum(counts.values())

counts, total_unknown

({'not found': np.int64(50),
  'tbc': np.int64(2),
  'n/a': np.int64(1),
  '-': np.int64(8),
  'variable': np.int64(4)},
 np.int64(65))

In [13]:
df.to_csv("gg.csv", index=False)

In [14]:
df.drop('Duration (Minutes)',axis = 1,inplace = True)

In [15]:
df

,Assessment Name,URL,Remote Support,Adaptive Support,Types,Description,Job Levels,Languages,Assessment Length,Assessment Length (minutes)
0,Account Manager Solution,https://www.shl.com/solutions/products/product...,Yes,Yes,"C, P, A, B",The Account Manager solution is an assessment ...,"Mid-Professional,","English (USA),",Approximate Completion Time in minutes = 49,49
1,Administrative Professional - Short Form,https://www.shl.com/solutions/products/product...,Yes,Yes,"A, K, P",The Administrative Professional solution is fo...,"Entry-Level,","English (USA),",Approximate Completion Time in minutes = 36,36
2,Agency Manager Solution,https://www.shl.com/solutions/products/product...,Yes,Yes,"A, B, P, S",The Agency Manager solution is for mid-level s...,"Front Line Manager, Manager, Supervisor,","English (USA),",Approximate Completion Time in minutes = 51,51
3,Apprentice + 8.0 Job Focused Assessment,https://www.shl.com/solutions/products/product...,Yes,No,"B, P",The Apprentice + 8.0 Job-Focused Assessment is...,"General Population, Graduate, Entry-Level,","English International, German,",Approximate Completion Time in minutes = 30,30
4,Apprentice 8.0 Job Focused Assessment,https://www.shl.com/solutions/products/product...,Yes,No,"B, P",The Apprentice 8.0 Job-Focused Assessment is a...,"Entry-Level, General Population, Graduate,","English International, German, French,",Approximate Completion Time in minutes = 20,20
...,...,...,...,...,...,...,...,...,...,...
479,Written English v1,https://www.shl.com/solutions/products/product...,Yes,Yes,K,The Written English test measures knowledge of...,"Entry-Level, Front Line Manager, Mid-Professio...","English (USA), English International,",Approximate Completion Time in minutes = 30,30
480,Written Spanish,https://www.shl.com/solutions/products/product...,Yes,Yes,K,This test measures knowledge of Spanish gramma...,"Entry-Level, Front Line Manager, Mid-Professio...","Latin American Spanish,",Approximate Completion Time in minutes = 22,22
481,Zabbix (New),https://www.shl.com/solutions/products/product...,Yes,No,K,Multi-choice test that measures the knowledge ...,"Mid-Professional, Professional Individual Cont...","English (USA),",Approximate Completion Time in minutes = 9,9
482,360 Digital Report,https://www.shl.com/solutions/products/product...,Yes,No,D,Introducing the new 360 Digital Report from SH...,"Director, Manager, Entry-Level, Executive, Fro...",Not Found,Not Found,-1
483,360° Multi-Rater Feedback System (MFS),https://www.shl.com/solutions/products/product...,Yes,No,D\nP,"SHL 360, or the Multi-Rater Feedback System (‘...","Director, Executive, Front Line Manager, Manag...","Latin American Spanish, Romanian, French (Cana...",Approximate Completion Time in minutes = Untimed,999

In [ ]:
df.to_csv("data/preprocessed.csv", index=False)

In [5]:
import pandas as pd
df = pd.read_csv('./final.csv')

In [6]:
# Mapping abbreviation to full name
type_mapping = {
    "A": "Ability & Aptitude",
    "B": "Biodata & Situational Judgement",
    "C": "Competencies",
    "D": "Development & 360",
    "E": "Assessment Exercises",
    "K": "Knowledge & Skills",
    "P": "Personality & Behavior",
    "S": "Simulations"
}
# Function to expand each abbreviation in a comma-separated string
def expand_types_abbreviations(types_str):
    return ", ".join([type_mapping.get(abbr.strip(), abbr.strip()) for abbr in types_str.split(",")])

# Apply to the column
df["Types"] = df["Types"].apply(expand_types_abbreviations)

In [7]:
df

,Assessment Name,URL,Remote Support,Adaptive Support,Types,Description,Job Levels,Languages,Assessment Length,Assessment Length (minutes)
0,Account Manager Solution,https://www.shl.com/solutions/products/product...,Yes,Yes,"Competencies, Personality & Behavior, Ability ...",The Account Manager solution is an assessment ...,"Mid-Professional,","English (USA),",Approximate Completion Time in minutes = 49,49
1,Administrative Professional - Short Form,https://www.shl.com/solutions/products/product...,Yes,Yes,"Ability & Aptitude, Knowledge & Skills, Person...",The Administrative Professional solution is fo...,"Entry-Level,","English (USA),",Approximate Completion Time in minutes = 36,36
2,Agency Manager Solution,https://www.shl.com/solutions/products/product...,Yes,Yes,"Ability & Aptitude, Biodata & Situational Judg...",The Agency Manager solution is for mid-level s...,"Front Line Manager, Manager, Supervisor,","English (USA),",Approximate Completion Time in minutes = 51,51
3,Apprentice + 8.0 Job Focused Assessment,https://www.shl.com/solutions/products/product...,Yes,No,"Biodata & Situational Judgement, Personality &...",The Apprentice + 8.0 Job-Focused Assessment is...,"General Population, Graduate, Entry-Level,","English International, German,",Approximate Completion Time in minutes = 30,30
4,Apprentice 8.0 Job Focused Assessment,https://www.shl.com/solutions/products/product...,Yes,No,"Biodata & Situational Judgement, Personality &...",The Apprentice 8.0 Job-Focused Assessment is a...,"Entry-Level, General Population, Graduate,","English International, German, French,",Approximate Completion Time in minutes = 20,20
...,...,...,...,...,...,...,...,...,...,...
479,Written English v1,https://www.shl.com/solutions/products/product...,Yes,Yes,Knowledge & Skills,The Written English test measures knowledge of...,"Entry-Level, Front Line Manager, Mid-Professio...","English (USA), English International,",Approximate Completion Time in minutes = 30,30
480,Written Spanish,https://www.shl.com/solutions/products/product...,Yes,Yes,Knowledge & Skills,This test measures knowledge of Spanish gramma...,"Entry-Level, Front Line Manager, Mid-Professio...","Latin American Spanish,",Approximate Completion Time in minutes = 22,22
481,Zabbix (New),https://www.shl.com/solutions/products/product...,Yes,No,Knowledge & Skills,Multi-choice test that measures the knowledge ...,"Mid-Professional, Professional Individual Cont...","English (USA),",Approximate Completion Time in minutes = 9,9
482,360 Digital Report,https://www.shl.com/solutions/products/product...,Yes,No,Development & 360,Introducing the new 360 Digital Report from SH...,"Director, Manager, Entry-Level, Executive, Fro...",Not Found,Not Found,-1
483,360° Multi-Rater Feedback System (MFS),https://www.shl.com/solutions/products/product...,Yes,No,D\nP,"SHL 360, or the Multi-Rater Feedback System (‘...","Director, Executive, Front Line Manager, Manag...","Latin American Spanish, Romanian, French (Cana...",Approximate Completion Time in minutes = Untimed,999

In [ ]:
df.to_csv("data/shl_product_catalog.csv", index=False)